### ISSUE TITLE
Some questions about main function in scr file

### ISSUE THREAD

**Issue by CopyDragon10086** [kishanrajput23/Training-Schedule-Management#1]
1.when i want to run the mian function of the scr file,in some pleces that to change file path,if you go to copy from your complete ,
it will "\" for your complete file path ,but when i to run it ,It will show that the file path is incorrectly formatted and must use "/" for your file path;(orther file path mabey will similarity )
2.on scr file it mabey not use #include<algorithm> ,but,you used transform function 

These are some problems I found in operation, and after I corrected them, the project can run normally, (thank you for providing such a good project, providing beginners practice)

**Comment by CopyDragon10086** [comment]
> 1.当我想运行SCR文件的MIAN函数时，在某些情况下，要更改文件路径，如果从完整的文件路径中复制，它将“\”作为完整的文件路径，但是当我运行它时，会显示文件路径格式不正确，必须使用“/”作为文件路径;（或者文件路径 mabey 将相似） 2.在SCR文件上，它不使用 #include，但是，您使用了转换功能
> 
> 这些是我在操作中发现的一些问题，我纠正后，项目可以正常运行，（感谢你们提供这么好的项目，提供初学者练习）

**Comment by CopyDragon10086** [comment]
> 1.when i want to run the mian function of the scr file,in some pleces that to change file path,if you go to copy from your complete , it will "\" for your complete file path ,but when i to run it ,It will show that the file path is incorrectly formatted and must use "/" for your file path;(orther file path mabey will similarity ) 2.on scr file it mabey not use #include ,but,you used transform function
> 
> These are some problems I found in operation, and after I corrected them, the project can run normally, (thank you for providing such a good project, providing beginners practice)

**Comment by kishanrajput23** [comment]
I'm glad to know that this project help you.
